apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-portfolio
  labels:
    app: my-portfolio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: app
        image: docker.io/ndeta100/myportfolio:4
        ports:
        - containerPort: 3000
